#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Función para manejar errores
handle_error() {
  echo "Error: $1" >&2
  exit 1
}

# 1. Revisar el formato del código con Prettier
npm run check-format || handle_error "El formato del código no es válido."

# 2. Ejecutar ESLint para revisar errores de estilo y calidad en el código
npm run check-lint || handle_error "Se encontraron errores de linting."

# 3. Verificar los tipos de TypeScript
npm run check-types || handle_error "Se encontraron errores de tipo en TypeScript."

# 4. Formatear el código si es necesario
npm run format || echo "Se ha formateado el código automáticamente."

# 5. Construir el proyecto para asegurarse de que no haya errores
npm run build || handle_error "La construcción del proyecto falló."
